'use strict';
const $ = selector => document.querySelector(selector);
const uid = prefix => `${prefix}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2, 7)}`;
const now = () => new Date().toISOString();
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[char]));
function emptyWorkspace() {
  return { version: 1, revision: 0, updatedAt: now(), projects: [], tasks: [], databank: [], people: [], activity: [] };
}
let state = emptyWorkspace(), sha = null, user = '', view = 'home', saveTimer;
const statuses = ['Created','Assigned','In Progress','Submitted','Under Review','Approved','Completed','Waiting for information','Waiting for external response','Blocked','Changes requested','On hold','Cancelled','Archived'];

function meta(record, creating = false) { const stamp = now(); if (creating) Object.assign(record,{createdAt:stamp,createdBy:user,revision:0}); Object.assign(record,{updatedAt:stamp,updatedBy:user,revision:(record.revision||0)+1}); state.revision++; state.updatedAt=stamp; }
function activity(type,title,detail,entityId){state.activity.unshift({id:uid('event'),type,title,detail,entityId,actor:user,createdAt:now()});state.activity=state.activity.slice(0,100)}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),2600)}
function syncStatus(type,text){const el=$('#sync');el.className=`sync ${type}`;el.innerHTML=`<i></i>${text}`}
function queueSave(summary='update workspace'){syncStatus('saving','SAVING');clearTimeout(saveTimer);saveTimer=setTimeout(()=>save(summary),650)}
async function save(summary){try{const result=await window.crowdnet.save({workspace:state,sha,summary});if(result.conflict){syncStatus('conflict','CONFLICT');toast('Bridge changed remotely. Restore before saving again.');return}sha=result.sha;syncStatus('saved','SAVED')}catch(error){syncStatus('conflict','RETRY REQUIRED');toast(error.message)}}
async function restore(){syncStatus('saving','RESTORING');try{const result=await window.crowdnet.restore();if(result.workspace)state=result.workspace;sha=result.sha;render();syncStatus(result.source==='cache'?'conflict':'saved',result.source==='cache'?'OFFLINE CACHE':'SAVED');toast(result.source==='cache'?'Bridge unavailable — local cache restored.':'Workspace restored from Bridge.')}catch(error){syncStatus('conflict','BRIDGE UNAVAILABLE');toast(error.message)}}

$('#login').addEventListener('submit',async event=>{event.preventDefault();const output=$('#loginMessage');output.textContent='VERIFYING PRIVATE BRIDGE…';try{const result=await window.crowdnet.authenticate({username:$('#username').value,accessKey:$('#accessKey').value,remember:$('#remember').checked});user=result.username;$('#auth').classList.add('hidden');$('#loader').classList.remove('hidden');setTimeout(()=>$('#loadStep').textContent='Restoring projects, tasks and activity…',400);const loaded=await window.crowdnet.restore();if(loaded.workspace)state=loaded.workspace;sha=loaded.sha;setTimeout(()=>{$('#loader').classList.add('hidden');$('#app').classList.remove('hidden');$('#currentUser').textContent=user.toUpperCase();$('#avatar').textContent=user[0].toUpperCase();render()},750)}catch(error){output.textContent=error.message}});
window.crowdnet.loadCredentials().then(saved=>{if(saved){$('#username').value=saved.username;$('#accessKey').value=saved.accessKey;$('#remember').checked=true}});
$('#restore').onclick=restore; $('#newProject').onclick=projectDialog;
$('#nav').onclick=event=>{const button=event.target.closest('button[data-view]');if(!button)return;view=button.dataset.view;document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x===button));render()};

function render(){const names={home:'COMMAND CENTER',projects:'PROJECT NETWORK',tasks:'TASK OPERATIONS',databank:'OPERATIONAL MEMORY',people:'RESPONSIBILITY NETWORK'};$('#breadcrumb').textContent=`CROWDNET / ${names[view]}`;$('#viewTitle').textContent=view==='home'?`Good evening, ${user}.`:names[view].replace(/\b\w/g,c=>c.toUpperCase());$('#content').innerHTML=({home:homeView,projects:projectsView,tasks:tasksView,databank:databankView,people:peopleView})[view]();bindContent()}
const statusClass=s=>s.toLowerCase().replaceAll(' ','-');
function homeView(){const blockers=state.tasks.filter(t=>t.status==='Blocked').length, review=state.tasks.filter(t=>['Submitted','Under Review'].includes(t.status)).length;return `<div class="metrics"><div class="metric"><b>${state.projects.length}</b><span>ACTIVE PROJECTS</span></div><div class="metric"><b>${state.tasks.filter(t=>!['Completed','Archived'].includes(t.status)).length}</b><span>OPEN TASKS</span></div><div class="metric"><b>${review}</b><span>WAITING REVIEW</span></div><div class="metric"><b>${blockers}</b><span>ACTIVE BLOCKERS</span></div></div><div class="hero-grid"><section class="panel"><div class="panel-title"><h3>LIVE BUSINESS TIMELINE</h3><small>${state.activity.length} events</small></div><div class="timeline">${state.activity.slice(0,12).map(event=>`<article class="event"><span class="event-icon">${event.type==='project'?'◇':'▣'}</span><div><strong>${esc(event.title)}</strong><p>${esc(event.detail)} · ${esc(event.actor)}</p></div><time>${new Date(event.createdAt).toLocaleDateString()}</time></article>`).join('')||'<div class="empty">No activity yet.</div>'}</div></section><section class="panel"><div class="panel-title"><h3>CURRENT PRIORITIES</h3></div>${state.projects.slice(0,3).map(project=>projectCard(project)).join('')}<div class="panel-title" style="margin-top:28px"><h3>ASSIGNED TO YOU</h3></div>${state.tasks.filter(t=>t.assignee.toLowerCase()===user.toLowerCase()).slice(0,4).map(taskRow).join('')||'<p class="empty">No assigned work.</p>'}</section></div>`}
function projectCard(p){return `<article class="project-card" data-project="${p.id}" style="--accent:${p.accent}"><div class="project-top"><div><span class="mono">${esc(p.stage)} / ${esc(p.priority)}</span><h3>${esc(p.name)}</h3></div><span class="tag">${esc(p.status)}</span></div><p>${esc(p.description)}</p><div class="progress"><i style="width:${p.progress}%"></i></div><p>${p.progress}% · NEXT: ${esc(p.nextAction)}</p></article>`}
function projectsView(){return `<div class="panel-title"><h3>PRIORITY ORDER · ${state.projects.length} PROJECTS</h3><small>Drag order is synchronized through the Bridge</small></div><div class="project-list">${state.projects.map(projectCard).join('')||'<div class="empty">No projects yet. Create the first project to begin.</div>'}</div>`}
function taskRow(t){return `<article class="task" data-task="${t.id}"><span class="drag">⠿</span><div><strong>${esc(t.title)}</strong><p>${esc(t.assignee)} · ${esc(state.projects.find(p=>p.id===t.projectId)?.name||'No project')}</p></div><span class="status ${statusClass(t.status)}">${esc(t.status)}</span></article>`}
function tasksView(){return `<div class="panel-title"><h3>ACTIVE TASK WORKSPACES</h3><button class="primary" id="quickTask">＋ NEW TASK</button></div><div class="task-list">${state.tasks.map(taskRow).join('')||'<div class="empty">No tasks yet. Tasks will appear here after they are created.</div>'}</div>`}
function databankView(){return `<input class="search" id="search" placeholder="Search confirmed answers, suppliers, decisions and keywords…"><div class="records" id="records">${recordsHtml(state.databank)}</div>`}
function recordsHtml(records){return records.map(r=>`<article class="record"><div class="project-top"><span class="mono">${esc(r.category)}</span><span class="status">${esc(r.reliability)}</span></div><h3>${esc(r.title)}</h3><p>${esc(r.answer)}</p><div class="tags">${r.keywords.map(k=>`<span class="tag">${esc(k)}</span>`).join('')}</div></article>`).join('')||'<div class="empty">No matching operational knowledge.</div>'}
function peopleView(){return `<div class="people-grid">${state.people.map(p=>{const assigned=state.tasks.filter(t=>t.assignee===p.name),active=assigned.filter(t=>!['Completed','Archived'].includes(t.status));return `<article class="panel person"><div class="big-avatar">${esc(p.name[0])}</div><span class="mono">${p.external?'EXTERNAL RESPONSIBILITY':'CROWDNET MEMBER'}</span><h2>${esc(p.name)}</h2><p>${esc(p.role)}</p><div class="metrics"><div class="metric"><b>${active.length}</b><span>ACTIVE</span></div><div class="metric"><b>${assigned.filter(t=>t.status==='Completed').length}</b><span>DONE</span></div></div></article>`}).join('')||'<div class="empty">No people have been added to this workspace.</div>'}</div>`}
function bindContent(){document.querySelectorAll('[data-project]').forEach(el=>el.onclick=()=>projectDialog(el.dataset.project));document.querySelectorAll('[data-task]').forEach(el=>el.onclick=()=>taskDialog(el.dataset.task));$('#quickTask')?.addEventListener('click',()=>taskDialog());$('#search')?.addEventListener('input',event=>{const q=event.target.value.toLowerCase();$('#records').innerHTML=recordsHtml(state.databank.filter(r=>JSON.stringify(r).toLowerCase().includes(q)))})}

function showModal(html){$('#modalBody').innerHTML=html;$('#modal').showModal()}
function projectDialog(id){const p=state.projects.find(x=>x.id===id);showModal(`<form id="projectForm" class="modal-content"><p class="mono">${p?'PROJECT DEVELOPMENT VIEW':'CREATE PROJECT'}</p><h2>${p?esc(p.name):'New project'}</h2><div class="form-grid"><label>NAME<input class="form-input" name="name" required value="${esc(p?.name||'')}"></label><label>STAGE<select class="form-input" name="stage">${['Idea','Research','Validation','Development','Launch','Growth'].map(x=>`<option ${p?.stage===x?'selected':''}>${x}</option>`)}</select></label><label class="wide">DESCRIPTION<textarea name="description">${esc(p?.description||'')}</textarea></label><label>PRIORITY<select class="form-input" name="priority">${['Critical','High','Medium','Low'].map(x=>`<option ${p?.priority===x?'selected':''}>${x}</option>`)}</select></label><label>PROGRESS<input class="form-input" name="progress" type="number" min="0" max="100" value="${p?.progress||0}"></label><label>CURRENT OBJECTIVE<input class="form-input" name="objective" value="${esc(p?.objective||'')}"></label><label>NEXT ACTION<input class="form-input" name="nextAction" value="${esc(p?.nextAction||'')}"></label><button class="primary wide">${p?'SAVE PROJECT':'CREATE PROJECT'}</button></div></form>`);$('#projectForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target));if(p){const oldStage=p.stage;Object.assign(p,data,{progress:Number(data.progress)});meta(p);if(oldStage!==p.stage)activity('project',`${p.name} advanced`,`${oldStage} → ${p.stage}`,p.id)}else{const item={id:uid('project'),...data,progress:Number(data.progress),status:'Active',accent:Math.random()>.5?'#8b62ff':'#43d9ff',members:[user]};meta(item,true);state.projects.push(item);activity('project',`${item.name} created`,'A new project entered the network',item.id)}$('#modal').close();render();queueSave(p?'update project':'create project')}}
function taskDialog(id){const t=state.tasks.find(x=>x.id===id);if(!t&&!state.projects.length){toast('Create a project before adding tasks.');return}showModal(`<form id="taskForm" class="modal-content"><p class="mono">${t?'TASK / '+esc(t.id):'CREATE TASK WORKSPACE'}</p><h2>${t?esc(t.title):'New assignment'}</h2><div class="form-grid"><label class="wide">TITLE<input class="form-input" name="title" required value="${esc(t?.title||'')}"></label><label>PROJECT<select class="form-input" name="projectId">${state.projects.map(p=>`<option value="${p.id}" ${t?.projectId===p.id?'selected':''}>${esc(p.name)}</option>`)}</select></label><label>ASSIGNEE<input class="form-input" name="assignee" value="${esc(t?.assignee||user)}"></label><label>STATUS<select class="form-input" name="status">${statuses.map(x=>`<option ${t?.status===x?'selected':''}>${x}</option>`)}</select></label><label>PRIORITY<select class="form-input" name="priority">${['Critical','High','Medium','Low'].map(x=>`<option ${t?.priority===x?'selected':''}>${x}</option>`)}</select></label><label class="wide">OBJECTIVE<textarea name="objective">${esc(t?.objective||'')}</textarea></label><label class="wide">INSTRUCTIONS<textarea name="instructions">${esc(t?.instructions||'')}</textarea></label><label class="wide">NOTES & RESEARCH<textarea name="notes">${esc(t?.notes||'')}</textarea></label><label class="wide">DRAFT ANSWER<textarea name="draftAnswer">${esc(t?.draftAnswer||'')}</textarea></label><label class="wide">FINAL CONFIRMED RESULT<textarea name="finalResult">${esc(t?.finalResult||'')}</textarea></label><label class="wide">REVIEW COMMENTS<textarea name="reviewComments">${esc(t?.reviewComments||'')}</textarea></label><button class="primary wide">SAVE TASK &amp; WORK</button></div></form>`);$('#taskForm').onsubmit=e=>{e.preventDefault();const data=Object.fromEntries(new FormData(e.target)),oldStatus=t?.status;if(t){Object.assign(t,data);meta(t)}else{const item={id:uid('task'),...data,creator:user};meta(item,true);state.tasks.push(item);activity('task',`${item.title} created`,`Assigned to ${item.assignee}`,item.id)}const item=t||state.tasks.at(-1);if(oldStatus&&oldStatus!==item.status)activity('status',`${item.title}: ${item.status}`,`${oldStatus} → ${item.status}`,item.id);if(item.status==='Completed'&&item.finalResult&&!state.databank.some(r=>r.taskId===item.id)){const record={id:uid('record'),title:item.title,answer:item.finalResult,projectId:item.projectId,taskId:item.id,completedBy:item.assignee,approvedBy:user,completionDate:now(),keywords:item.title.toLowerCase().split(/\W+/).filter(x=>x.length>3),category:'Task result',reliability:'Confirmed'};meta(record,true);state.databank.unshift(record);activity('databank',`${item.title} preserved`,'Final result converted into confirmed knowledge',record.id);toast('Task completed · Databank record generated')}$('#modal').close();render();queueSave('update task workspace')}}

// Lightweight, visibility-aware space field.
const canvas=$('#space'),ctx=canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:60},()=>[Math.random()*innerWidth,Math.random()*innerHeight,Math.random()+.2])}function draw(){if(!document.hidden){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#7382ad';stars.forEach(s=>{s[1]=(s[1]+s[2]*.04)%innerHeight;ctx.globalAlpha=s[2]*.25;ctx.fillRect(s[0],s[1],s[2],s[2])})}requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
